# Comments are provided throughout this file to help you get started.
# If you need more help, visit the Docker Compose reference guide at
# https://docs.docker.com/go/compose-spec-reference/

# Here the instructions define your application as a service called "server".
# This service is built from the Dockerfile in the current directory.
# You can add other services your application may depend on here, such as a
# database or a cache. For examples, see the Awesome Compose repository:
# https://github.com/docker/awesome-compose
services:
  server:
    build:
      context: .
    ports:
      - 8080:8080
    env_file: .env
    depends_on:
       db:
         condition: service_healthy
    develop :
      watch :
        - action : rebuild
          path : .
    command :
      - python
      - -m
      - uvicorn
      - main:app
      - --host=0.0.0.0
      - --port=8080
#  db:
#     image: my_db
#     restart: always
#     volumes:
#       - db-data:/var/lib/postgresql/data
#     env_file: .env
#     environment:
#       - POSTGRES_DB=${POSTGRES_SERVER}
#       - POSTGRES_USER=${POSTGRES_USER}
#       - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
#       - POSTGRES_DB=${POSTGRES_DB}
#       - POSTGRES_PORT=${POSTGRES_PORT}
#     expose:
#       - 5432
#     healthcheck:
#       test: [ "CMD", "pg_isready" ]
#       interval: 60s
#       timeout: 30s
#       retries: 5
#volumes:
#   db-data: