services:
  server:
    build:
      context: .
    ports:
      - 8080:8080
    env_file: .env
    depends_on:
       db:
         condition: service_healthy
    develop :
      watch :
        - action : rebuild
          path : .
    command :
      - python
      - -m
      - uvicorn
      - main:app
      - --host=0.0.0.0
      - --port=8080
#  db:
#     image: my_db
#     restart: always
#     volumes:
#       - db-data:/var/lib/postgresql/data
#     env_file: .env
#     environment:
#       - POSTGRES_DB=${POSTGRES_SERVER}
#       - POSTGRES_USER=${POSTGRES_USER}
#       - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
#       - POSTGRES_DB=${POSTGRES_DB}
#       - POSTGRES_PORT=${POSTGRES_PORT}
#     expose:
#       - 5432
#     healthcheck:
#       test: [ "CMD", "pg_isready" ]
#       interval: 60s
#       timeout: 30s
#       retries: 5
#volumes:
#   db-data: